### ISSUE TITLE
Urgent!!!

### ISSUE THREAD

**Issue by shashwat010** [dungngminh/happy-care-mobile#1]
Hello sir, could you please make your backend URL public for sometime. Need to show for our university project.

**Comment by shashwat010** [comment]
Or could you please provide apk file for the app.

**Comment by dungngminh** [comment]
Hi, I have sent a mail for your friend EKANSH for 3 days ago

**Comment by dungngminh** [comment]
You can check this backend site link: https://github.com/derektruong/happy-care-server
